<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.automation.APIautomationFramework.testcases.CreateCustomerTest" tests="4" time="2.079" ignored="0" failures="1" timestamp="24 Jul 2020 01:57:52 GMT" skipped="2" hostname="DESKTOP-MD2112N" errors="0">
  <testcase name="CreateCustomerAPIValid" time="0.001" classname="com.automation.APIautomationFramework.testcases.CreateCustomerTest">
    <skipped/>
  </testcase> <!-- CreateCustomerAPIValid -->
  <testcase name="CreateCustomerAPIInvalid" time="1.524" classname="com.automation.APIautomationFramework.testcases.CreateCustomerTest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [401]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at org.testng.Assert.assertEquals(Assert.java:399)
	at com.automation.APIautomationFramework.testcases.CreateCustomerTest.CreateCustomerAPIInvalid(CreateCustomerTest.java:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- CreateCustomerAPIInvalid -->
  <testcase name="CreateCustomerAPIValid" time="0.553" classname="com.automation.APIautomationFramework.testcases.CreateCustomerTest"/>
  <testcase name="CreateCustomerAPIValid" time="0.001" classname="com.automation.APIautomationFramework.testcases.CreateCustomerTest">
    <skipped/>
  </testcase> <!-- CreateCustomerAPIValid -->
</testsuite> <!-- com.automation.APIautomationFramework.testcases.CreateCustomerTest -->
